web_homepage:
    path:   /
    defaults: { _controller: WebBundle:Default:index }

web_search_results:
    path:   /searchresults
    defaults: { _controller: WebBundle:Default:search }

cookies:
    path:   /cookies_policy
    defaults: { _controller: WebBundle:Default:cookiesSee }
