product_see:
    path:   /product/{product_slug}
    defaults: { _controller: ProductBundle:Product:see , product_slug: null}

product_edit:
    path:   /product/{product_slug}/edit
    defaults: { _controller: ProductBundle:Product:edit , product_slug: null }

category_see:
    path:   /category/{category_slug}
    defaults: { _controller: ProductBundle:category:see , category_slug: null}
